name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag smtp-mailhog-testing:$(date +%s)
    - name: Lint with flake8
      run: |
        docker run -t smtp-mailhog-testing:$(date +%s) flake8
    - name: Test with pytest
      run: |
        docker-compose up
